version: "3.7"

networks:
  api_redis:

services:
  api:
    container_name: carfax-api
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - db
      - redis
    networks:
      - api_redis
      - default

  db:
    image: mongo:4.0.4
    container_name: carfax-db
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: carfax-redis
    expose:
      - 6379
    networks:
      - api_redis

