version: "3.7"

services:
  api:
    container_name: carfax-api
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mongo:4.0.4
    container_name: carfax-db
    ports:
      - 27017:27017
